### PR TITLE
Add Corporation Listing and Dashboard Tweaks

### PR DESCRIPTION
**Pull request by mglinski**
Follow user settings for number formats on dashboard
Add Corporation Listing Table to show all corps at once
Add Corp Count and Corp ISK Total to Dashboard

### CODE REVIEW

**Comment by eve-seat** [comment]
Whats the deal with all the email style changes? Tabbing/spacing problem?
We also need to squash this to 1/2 commits :P

**Comment by mglinski** [comment]
The style files I think are line ending normalizations, my editor prolly did it without me noticing.

**Comment by mglinski** [comment]
I can do the work to squash it down, but wont really do anything beneficial. I personally like to keep the history of all commits so you can git bisect in the future and not have to sort through huge file changes to hunt down bugs.

**Comment by mglinski** [comment]
Also screenshot of the page: http://cl.ly/image/3L3t1U2Q3G2n

**Pull request merged**
