### PR TITLE
Fix sovereignty bonus on tower strontium consumption and improve algo

### PR DESCRIPTION
**Pull request by warlof**
* Add sovereignty bonus to the strontium consumption
* Replace hard code fuel/stront reduction if tower are in sovereignty by 0.75 rate
* Merge fuel and stront consumption in a global array
* Replace the if/elseif/else statement which check the tower size by a lookup into a global consumption array

### CODE REVIEW

**Comment by Zumochi** [comment]
This is nice but it also needs faction towers. The page on the Evelopedia is still accurate AFAIK to use as source: https://wiki.eveonline.com/en/wiki/Starbase#Fuel_Usage

**Comment by MilosRasic** [comment]
```
$tower_size = $tower_type_name[3];
```
is not a good was to get tower size, because of already mentioned faction towers but especially since Large towers won't have Large in the end. A quick and dirty fix:
```
            $tower_size = $tower_type_name[count($tower_type_name) - 1];
            if ($tower_size == 'Tower')
            	$tower_size = 'Large';
```

**Comment by warlof** [comment]
Well, faction tower are not yet take in charge. So not fault of my commit.
I'm working on an improvement.

**Comment by warlof** [comment]
fix in #400

**Pull request closed without merging**
