### PR TITLE
adding smtp port and encryption to the env vars

### PR DESCRIPTION
**Pull request by warlof**

### CODE REVIEW

**Comment by eve-seat** [comment]
This dupes a lil with #310

**Comment by warlof** [comment]
both should be merged, i've add the setup file modification :)

didn't saw this PR. I've corrected the indentation.

**Comment by ccatlett1984** [comment]
Qu1ckkk, do you want of us to add the changes to our PR? or just merge both of them?

**Comment by warlof** [comment]
Oh yeah, you can make the merge ccatlett1984. You saw the config miss first. Just take the install file, the our mail conf is the same =)

**Comment by eve-seat** [comment]
Will do @ccatlett1984 's one. As for the install changes, I would like to have it like the mail drive validate the potential choices.

**Pull request merged**
